# Generated by Django 5.1.1 on 2024-10-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_applied',
            field=models.BooleanField(default=False),
        ),
    ]
